import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import {
  ACCENTS,
  ACCENT_COOKIE,
  DEFAULT_ACCENT,
  DEFAULT_MODE,
  MODE_COOKIE,
} from "@/lib/theme";
import { setRequestLocale, getTranslations } from "next-intl/server";
import { routing, localeDirection } from "@/i18n/routing";
import { fontVariables } from "@/lib/fonts";
import { PostHogProvider } from "@/components/providers/PostHogProvider";
import { ChatProvider } from "@/components/chat/ChatProvider";
import { SiteNav } from "@/components/layout/SiteNav";
import { SiteFooter } from "@/components/layout/SiteFooter";
import { ChatDock } from "@/components/chat/ChatDock";
import { ConsentBanner } from "@/components/layout/ConsentBanner";
import { ScrollReveal } from "@/components/providers/ScrollReveal";
import { ScrollProgress } from "@/components/motion/ScrollProgress";
import "@/styles/globals.css";

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

type LayoutProps = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "meta" });
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://stryvia.ai";

  return {
    metadataBase: new URL(siteUrl),
    title: {
      default: t("title"),
      template: "%s · Stryvia",
    },
    description: t("description"),
    applicationName: "Stryvia",
    alternates: {
      canonical: locale === routing.defaultLocale ? "/" : `/${locale}`,
      languages: {
        en: "/",
        ar: "/ar",
        fr: "/fr",
      },
    },
    openGraph: {
      type: "website",
      siteName: "Stryvia",
      title: t("title"),
      description: t("description"),
      locale: locale === "ar" ? "ar_SA" : "en_US",
    },
    twitter: {
      card: "summary_large_image",
      title: t("title"),
      description: t("description"),
    },
    // Icons (favicon, apple-icon) and the OG/Twitter images are generated by the
    // file-based metadata routes: app/icon.tsx, app/apple-icon.tsx,
    // app/opengraph-image.tsx, app/twitter-image.tsx.
  };
}

export default async function LocaleLayout({ children, params }: LayoutProps) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  setRequestLocale(locale);

  const dir = localeDirection[locale] ?? "ltr";
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://stryvia.ai";

  // Pages stay statically generated; the saved theme (cookie) is applied by the
  // pre-paint inline script below, so there's no flash and no per-request
  // rendering. The server-rendered attributes are the brand defaults.
  const accentIds = ACCENTS.map((a) => a.id);
  const themeScript =
    `(function(){try{var d=document.documentElement,c=document.cookie;` +
    `var m=(c.match(/(?:^|; )${MODE_COOKIE}=([^;]+)/)||[])[1];` +
    `var a=(c.match(/(?:^|; )${ACCENT_COOKIE}=([^;]+)/)||[])[1];` +
    `if(!m){m=window.matchMedia&&window.matchMedia('(prefers-color-scheme: light)').matches?'light':'${DEFAULT_MODE}';}` +
    `d.dataset.theme=m==='light'?'light':'dark';` +
    `var A=${JSON.stringify(accentIds)};` +
    `d.dataset.accent=A.indexOf(a)>-1?a:'${DEFAULT_ACCENT}';` +
    `}catch(e){}})();`;

  // Organization + WebSite structured data (Spec §8).
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        name: "Stryvia",
        url: siteUrl,
        description: "The intelligence you build with.",
        slogan: "The intelligence you build with.",
      },
      {
        "@type": "WebSite",
        name: "Stryvia",
        url: siteUrl,
        inLanguage: locale,
      },
    ],
  };

  return (
    <html
      lang={locale}
      dir={dir}
      data-theme={DEFAULT_MODE}
      data-accent={DEFAULT_ACCENT}
      className={fontVariables}
      suppressHydrationWarning
    >
      <head>
        {/* Apply the saved theme (or OS preference on first visit) before paint
            so there's no flash and pages can stay statically generated. */}
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        {/* Without JS, never leave reveal content hidden. */}
        <noscript>
          <style>{`.sv-reveal,.sv-scene{opacity:1 !important}.sv-word-inner{opacity:1 !important;transform:none !important}`}</style>
        </noscript>
      </head>
      <body>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <NextIntlClientProvider>
          <PostHogProvider>
            <ChatProvider>
              <ScrollReveal />
              <ScrollProgress />
              {/* Atmosphere layers (A.6) sit behind everything, non-interactive */}
              <div className="sv-aurora" aria-hidden="true">
                <span className="a1" />
                <span className="a2" />
                <span className="a3" />
              </div>
              <div className="sv-vignette" aria-hidden="true" />
              <div className="sv-grain" aria-hidden="true" />

              <SiteNav />
              <main id="main">{children}</main>
              <SiteFooter />
              <ChatDock />
              <ConsentBanner />
            </ChatProvider>
          </PostHogProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
